# Generated by Django 5.2 on 2025-07-01 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_room_booking_delete_user'),
    ]

    operations = [
    migrations.AddField(
        model_name='room',
        name='name',
        field=models.CharField(max_length=100, default='Room'),
    ),
    migrations.AddField(
        model_name='room',
        name='capacity',
        field=models.PositiveIntegerField(default=1),
    ),
]