# Generated by Django 5.2 on 2025-07-02 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0004_rename_type_room_room_type_alter_room_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='type',
            field=models.CharField(choices=[('standard', 'Standard'), ('private', 'Private')], default=2, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('standard', 'Standard'), ('private', 'Private')], max_length=20),
        ),
    ]
