# Generated by Django 5.2 on 2025-07-05 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0006_remove_room_room_type_alter_room_capacity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='type',
            new_name='room_type',
        ),
    ]
