# Generated by Django 5.2 on 2025-07-07 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0007_rename_type_room_room_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
