# Generated by Django 5.2 on 2025-07-07 11:03

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20250705_2116'),
    ]

operations = [
    migrations.AddField(
        model_name='room',
        name='name',
        field=models.CharField(max_length=100, default='Room'),
    ),
    migrations.AddField(
        model_name='room',
        name='capacity',
        field=models.PositiveIntegerField(default=1),
    ),
]
